 <?php
 class FisaStingere {
	private $id;
	public function __construct($connection=null, $id="") {
        require_once "verifyid.class.php"; // verifica daca userul poate modifica interventia cu id-ul
        $verifyid = new Verifyid($connection);
        $verif=$verifyid->verifyStingere($connection,$id);
        if(!$verif)exit();
        $parameters[] = $id;
  		  foreach($_SESSION['subunit_acces'] as $cod){
        	$conditions[] = 's.struct = ? ';
        	$parameters[] = $cod;
        }
    		$sqll = implode(" OR ", $conditions);
    		$sqlstat = 'SELECT s.struct,s.igsu,s.isu,s.subunit,s.participanti,s.tipsubunitate,s.codsubunit,s.categ_interv,s.tip_interv,
s.cod_interv,s.alertare,s.nume_victima,s.svsu_spsualte,s.tara,s.judet,s.localitati,s.sate,s.adresa,
s.laty,s.longx,s.distanta_km,s.plecare,s.anunt,s.sosire,s.producere,s.localizare,s.lichidare,
s.retragere,s.sosiresvsu,s.sosirespsu,s.organtutelar,s.tipproprietate,s.codactivitateeconom,s.tipobiectiv,
s.cod_dest,s.cos_fum,s.forte_cerute_in_sprijin,s.procedee_intrerupere,s.comandant_actiune,s.comandant_interventie,
s.crestere_capacitate,s.personal_destinat_ofiter,s.personal_destinat_maistru,s.personal_destinat_subofiter,
s.personal_destinat_voluntar,s.personal_destinat_primar,s.personal_destinat_viceprimar,s.personal_destinat_secretar,
s.personal_destinat_svsu,s.personal_destinat_spsu,s.personal_destinat_politie,s.personal_destinat_jandarmi,
s.personal_destinat_frontiera,s.personal_destinat_armata,s.personal_destinat_cetateni,s.mijstingere_isu,
s.mijstingere_svsu,s.mijstingere_spsu,s.mijstingere_isu_tipb,s.mijstingere_svsu_tipb,s.mijstingere_spsu_tipb,
s.mijstingere_isu_tipc,s.mijstingere_svsu_tipc,s.mijstingere_spsu_tipc,s.mijstingere_isu_tipd,
s.mijstingere_svsu_tipd,s.mijstingere_spsu_tipd,s.mijstingere_isu_tevigen,s.mijstingere_svsu_tevigen,
s.mijstingere_spsu_tevigen,s.mijstingere_isu_refpulb,s.mijstingere_svsu_refpulb,s.mijstingere_spsu_refpulb,
s.mijstingere_isu_autostin,s.mijstingere_svsu_autosting,s.mijstingere_spsu_autosting,s.tipurgenta_multirisc_1,
s.tipurgenta_multirisc_2,s.tipurgenta_multirisc_3,s.tipurgenta_multirisc_4,s.tipurgenta_multirisc_svsu,
s.tipurgenta_multirisc_spsu,s.tipurgenta_pma2_1,s.tipurgenta_pma2_2,s.tipurgenta_pma2_3,s.tipurgenta_pma2_4,
s.tipurgenta_pma2_svsu,s.tipurgenta_pma2_spsu,s.tipurgenta_pma1_1,s.tipurgenta_pma1_2,s.tipurgenta_pma1_3,
s.tipurgenta_pma1_4,s.tipurgenta_pma1_svsu,s.tipurgenta_pma1_spsu,s.tipurgenta_asasmare_1,
s.tipurgenta_asasmare_2,s.tipurgenta_asasmare_3,s.tipurgenta_asasmare_4,s.tipurgenta_asasmare_svsu,
s.tipurgenta_asasmare_spsu,s.tipurgenta_asasmedie_1,s.tipurgenta_asasmedie_2,s.tipurgenta_asasmedie_3,
s.tipurgenta_asasmedie_4,s.tipurgenta_asasmedie_svsu,s.tipurgenta_asasmedie_spsu,s.tipurgenta_asasmica_1,
s.tipurgenta_asasmica_2,s.tipurgenta_asasmica_3,s.tipurgenta_asasmica_4,s.tipurgenta_asasmica_svsu,
s.tipurgenta_asasmica_spsu,s.tipurgenta_alteasas_1,s.tipurgenta_alteasas_2,s.tipurgenta_alteasas_3,
s.tipurgenta_alteasas_4,s.tipurgenta_alteasas_svsu,s.tipurgenta_alteasas_spsu,s.tipurgenta_aisi_1,
s.tipurgenta_aisi_2,s.tipurgenta_aisi_3,s.tipurgenta_aisi_4,s.tipurgenta_aisi_svsu,s.tipurgenta_aisi_spsu,
s.tipurgenta_aspfgi_1,s.tipurgenta_aspfgi_2,s.tipurgenta_aspfgi_3,s.tipurgenta_aspfgi_4,s.tipurgenta_aspfgi_svsu,
s.tipurgenta_aspfgi_spsu,s.tipurgenta_aservamop_1,s.tipurgenta_aservamop_2,s.tipurgenta_aservamop_3,
s.tipurgenta_aservamop_4,s.tipurgenta_aservamop_svsu,s.tipurgenta_aservamop_spsu,s.tipurgenta_crbnadp_1,
s.tipurgenta_crbnadp_2,s.tipurgenta_crbnadp_3,s.tipurgenta_crbnadp_4,s.tipurgenta_crbnadp_svsu,
s.tipurgenta_crbnadp_spsu,s.tipurgenta_aci_1,s.tipurgenta_aci_2,s.tipurgenta_aci_3,s.tipurgenta_aci_4,
s.tipurgenta_aci_svsu,s.tipurgenta_aci_spsu,s.tipurgenta_aspscaf_1,s.tipurgenta_aspscaf_2,s.tipurgenta_aspscaf_3,
s.tipurgenta_aspscaf_4,s.tipurgenta_aspscaf_svsu,s.tipurgenta_aspscaf_spsu,s.tipurgenta_barcisalupe_1,
s.tipurgenta_barcisalupe_2,s.tipurgenta_barcisalupe_3,s.tipurgenta_barcisalupe_4,s.tipurgenta_barcisalupe_svsu,
s.tipurgenta_barcisalupe_spsu,s.tipurgenta_afzm_1,s.tipurgenta_afzm_2,s.tipurgenta_afzm_3,s.tipurgenta_afzm_4,
s.tipurgenta_afzm_svsu,s.tipurgenta_afzm_spsu,s.tipurgenta_ambulante_1,s.tipurgenta_ambulante_2,s.tipurgenta_ambulante_3,
s.tipurgenta_ambulante_4,s.tipurgenta_ambulante_svsu,s.tipurgenta_ambulante_spsu,s.tipurgenta_descarc_1,
s.tipurgenta_descarc_2,s.tipurgenta_descarc_3,s.tipurgenta_descarc_4,s.tipurgenta_descarc_svsu,s.tipurgenta_descarc_spsu,
s.tipurgenta_asptransportapa_1,s.tipurgenta_asptransportapa_2,s.tipurgenta_asptransportapa_3,s.tipurgenta_asptransportapa_4,
s.tipurgenta_asptransportapa_svsu,s.tipurgenta_asptransportapa_spsu,s.tipurgenta_mptmpr_1,s.tipurgenta_mptmpr_2,
s.tipurgenta_mptmpr_3,s.tipurgenta_mptmpr_4,s.tipurgenta_mptmpr_svsu,s.tipurgenta_mptmpr_spsu,s.tipurgenta_alteautospeciale_1,
s.tipurgenta_alteautospeciale_2,s.tipurgenta_alteautospeciale_3,s.tipurgenta_alteautospeciale_4,s.tipurgenta_alteautospeciale_svsu,
s.tipurgenta_alteautospeciale_spsu,s.pers_salvate_adulti,s.pers_salvate_copii,s.pers_evacuate_adulti,s.pers_evacuate_copii,
s.deces_altesit_altep,s.deces_altesit_copii,s.deces_altesit_isu,s.deces_altesit_svsu,s.deces_ars_altep,s.deces_ars_copii,
s.deces_ars_isu,s.deces_ars_svsu,s.deces_asfix_altep,s.deces_asfix_copii,s.deces_asfix_isu,s.deces_asfix_svsu,s.ranit_altesit_copii,
s.ranit_altesit_isu,s.ranit_altesit_svsu,s.ranit_altesitx_altep,s.ranit_ars_altep,s.ranit_ars_copii,s.ranit_ars_isu,
s.ranit_ars_svsu,s.ranit_asfix_altep,s.ranit_asfix_copii,s.ranit_asfix_isu,s.ranit_asfix_svsu,s.deced06,s.deced25,
s.deced55,s.deced70,s.deced71,s.deced714,s.ranit06,s.ranit25,s.ranit55,s.ranit70,s.ranit71,s.ranit714,s.contam06,
s.contam25,s.contam55,s.contam70,s.contam71,s.contam714,s.anim_mari_contam,s.anim_mari_moarte,s.anim_mari_ranite,
s.anim_mici_contam,s.anim_mici_moarte,s.anim_mici_ranite,s.anim_pasari_contam,s.anim_pasari_moarte,s.anim_pasari_ranite,
s.munitie_asanat_bombe_artilerie,s.munitie_asanat_grenade,s.munitie_asanat_grenade_defens,s.munitie_asanat_proiectil,
s.bombe_aviatie,s.mine_antitanc,s.mine_antipers,s.mine_marine,s.aruncator_gren,s.muninfanterie,s.alte_munitii,
s.val_distr,s.val_salv,s.sursa_probabila,s.mijloc_producere,s.primul_mat_ars,s.imprejur_determ,s.despreob1,
s.despreob2,s.despreob3,s.despreob4,s.despreob5,s.despreob6,s.despreob7,s.codsubst1,s.codsubst2,s.codsubst3,
s.codsubst4,s.numesubst1,s.numesubst2,s.numesubst3,s.numesubst4,s.codpericol1,s.codpericol2,s.codpericol3,s.codpericol4,
s.elib_subst_apa,s.elib_subst_aer,s.elib_subst_sol,s.tip_radionuclid, s.act_sursei,s.debit_doza,s.caract_sursa,s.alte_masuri_protective,
s.contramasuri,s.contramasuri_scurt,s.anticip_sever,s.evol_inciden,s.consecinte_even,s.date_suplimentare,s.zonademortalitate,
s.distanta_adapostire,s.zonadeintoxicatie,s.distanta_evacuare,s.profilaxiacuiod,s.restrictiialimente1,s.restrictiialimente2,
s.restrictiialimente3,s.restrictiialimente4,s.restrictiialimente5,s.restrictiialimente6,s.dozaacumulata,s.distanta1,
s.distanta2,s.distanta3,s.distanta4,s.distanta5,s.distanta6,s.distanta7,s.distanta8,s.doza1,s.doza2,s.doza3,s.doza4,
s.doza5,s.doza6,s.doza7,s.doza8,s.doza_int_sapt,s.doza_int_luna,s.doza_int_zi,s.suprafata_afectata,s.expl_mun,
s.zona_afect,s.nr_gospodarii,s.asist_spec,s.masuri_su,s.poluaretransf,s.verific_raport, s.intravilan, s.gradcontaminare, 
s.telefon FROM intStingere s WHERE s.id = ? AND ('.$sqll.') LIMIT 1';
  $stmt = $connection->prepare($sqlstat);
  $stmt->bind_param(str_repeat("s", count($parameters)), ...$parameters);
  $stmt->execute();
  $stmt->store_result();
  $stmt->bind_result($struct,$igsu,$isu,$subunit,$participanti,$tipsubunitate,$codsubunit,$categ_interv,$tip_interv,
$cod_interv,$alertare,$nume_victima,$svsu_spsualte,$tara,$judet,$localitati,$sate,$adresa,
$laty,$longx,$distanta_km,$plecare,$anunt,$sosire,$producere,$localizare,$lichidare,
$retragere,$sosiresvsu,$sosirespsu,$organtutelar,$tipproprietate,$codactivitateeconom,$tipobiectiv,
$cod_dest,$cos_fum,$forte_cerute_in_sprijin,$procedee_intrerupere,$comandant_actiune,$comandant_interventie,
$crestere_capacitate,$personal_destinat_ofiter,$personal_destinat_maistru,$personal_destinat_subofiter,
$personal_destinat_voluntar,$personal_destinat_primar,$personal_destinat_viceprimar,$personal_destinat_secretar,
$personal_destinat_svsu,$personal_destinat_spsu,$personal_destinat_politie,$personal_destinat_jandarmi,
$personal_destinat_frontiera,$personal_destinat_armata,$personal_destinat_cetateni,$mijstingere_isu,
$mijstingere_svsu,$mijstingere_spsu,$mijstingere_isu_tipb,$mijstingere_svsu_tipb,$mijstingere_spsu_tipb,
$mijstingere_isu_tipc,$mijstingere_svsu_tipc,$mijstingere_spsu_tipc,$mijstingere_isu_tipd,
$mijstingere_svsu_tipd,$mijstingere_spsu_tipd,$mijstingere_isu_tevigen,$mijstingere_svsu_tevigen,
$mijstingere_spsu_tevigen,$mijstingere_isu_refpulb,$mijstingere_svsu_refpulb,$mijstingere_spsu_refpulb,
$mijstingere_isu_autostin,$mijstingere_svsu_autosting,$mijstingere_spsu_autosting,$tipurgenta_multirisc_1,
$tipurgenta_multirisc_2,$tipurgenta_multirisc_3,$tipurgenta_multirisc_4,$tipurgenta_multirisc_svsu,
$tipurgenta_multirisc_spsu,$tipurgenta_pma2_1,$tipurgenta_pma2_2,$tipurgenta_pma2_3,$tipurgenta_pma2_4,
$tipurgenta_pma2_svsu,$tipurgenta_pma2_spsu,$tipurgenta_pma1_1,$tipurgenta_pma1_2,$tipurgenta_pma1_3,
$tipurgenta_pma1_4,$tipurgenta_pma1_svsu,$tipurgenta_pma1_spsu,$tipurgenta_asasmare_1,
$tipurgenta_asasmare_2,$tipurgenta_asasmare_3,$tipurgenta_asasmare_4,$tipurgenta_asasmare_svsu,
$tipurgenta_asasmare_spsu,$tipurgenta_asasmedie_1,$tipurgenta_asasmedie_2,$tipurgenta_asasmedie_3,
$tipurgenta_asasmedie_4,$tipurgenta_asasmedie_svsu,$tipurgenta_asasmedie_spsu,$tipurgenta_asasmica_1,
$tipurgenta_asasmica_2,$tipurgenta_asasmica_3,$tipurgenta_asasmica_4,$tipurgenta_asasmica_svsu,
$tipurgenta_asasmica_spsu,$tipurgenta_alteasas_1,$tipurgenta_alteasas_2,$tipurgenta_alteasas_3,
$tipurgenta_alteasas_4,$tipurgenta_alteasas_svsu,$tipurgenta_alteasas_spsu,$tipurgenta_aisi_1,
$tipurgenta_aisi_2,$tipurgenta_aisi_3,$tipurgenta_aisi_4,$tipurgenta_aisi_svsu,$tipurgenta_aisi_spsu,
$tipurgenta_aspfgi_1,$tipurgenta_aspfgi_2,$tipurgenta_aspfgi_3,$tipurgenta_aspfgi_4,$tipurgenta_aspfgi_svsu,
$tipurgenta_aspfgi_spsu,$tipurgenta_aservamop_1,$tipurgenta_aservamop_2,$tipurgenta_aservamop_3,
$tipurgenta_aservamop_4,$tipurgenta_aservamop_svsu,$tipurgenta_aservamop_spsu,$tipurgenta_crbnadp_1,
$tipurgenta_crbnadp_2,$tipurgenta_crbnadp_3,$tipurgenta_crbnadp_4,$tipurgenta_crbnadp_svsu,
$tipurgenta_crbnadp_spsu,$tipurgenta_aci_1,$tipurgenta_aci_2,$tipurgenta_aci_3,$tipurgenta_aci_4,
$tipurgenta_aci_svsu,$tipurgenta_aci_spsu,$tipurgenta_aspscaf_1,$tipurgenta_aspscaf_2,$tipurgenta_aspscaf_3,
$tipurgenta_aspscaf_4,$tipurgenta_aspscaf_svsu,$tipurgenta_aspscaf_spsu,$tipurgenta_barcisalupe_1,
$tipurgenta_barcisalupe_2,$tipurgenta_barcisalupe_3,$tipurgenta_barcisalupe_4,$tipurgenta_barcisalupe_svsu,
$tipurgenta_barcisalupe_spsu,$tipurgenta_afzm_1,$tipurgenta_afzm_2,$tipurgenta_afzm_3,$tipurgenta_afzm_4,
$tipurgenta_afzm_svsu,$tipurgenta_afzm_spsu,$tipurgenta_ambulante_1,$tipurgenta_ambulante_2,$tipurgenta_ambulante_3,
$tipurgenta_ambulante_4,$tipurgenta_ambulante_svsu,$tipurgenta_ambulante_spsu,$tipurgenta_descarc_1,
$tipurgenta_descarc_2,$tipurgenta_descarc_3,$tipurgenta_descarc_4,$tipurgenta_descarc_svsu,$tipurgenta_descarc_spsu,
$tipurgenta_asptransportapa_1,$tipurgenta_asptransportapa_2,$tipurgenta_asptransportapa_3,$tipurgenta_asptransportapa_4,
$tipurgenta_asptransportapa_svsu,$tipurgenta_asptransportapa_spsu,$tipurgenta_mptmpr_1,$tipurgenta_mptmpr_2,
$tipurgenta_mptmpr_3,$tipurgenta_mptmpr_4,$tipurgenta_mptmpr_svsu,$tipurgenta_mptmpr_spsu,$tipurgenta_alteautospeciale_1,
$tipurgenta_alteautospeciale_2,$tipurgenta_alteautospeciale_3,$tipurgenta_alteautospeciale_4,$tipurgenta_alteautospeciale_svsu,
$tipurgenta_alteautospeciale_spsu,$pers_salvate_adulti,$pers_salvate_copii,$pers_evacuate_adulti,$pers_evacuate_copii,
$deces_altesit_altep,$deces_altesit_copii,$deces_altesit_isu,$deces_altesit_svsu,$deces_ars_altep,$deces_ars_copii,
$deces_ars_isu,$deces_ars_svsu,$deces_asfix_altep,$deces_asfix_copii,$deces_asfix_isu,$deces_asfix_svsu,$ranit_altesit_copii,
$ranit_altesit_isu,$ranit_altesit_svsu,$ranit_altesitx_altep,$ranit_ars_altep,$ranit_ars_copii,$ranit_ars_isu,
$ranit_ars_svsu,$ranit_asfix_altep,$ranit_asfix_copii,$ranit_asfix_isu,$ranit_asfix_svsu,$deced06,$deced25,
$deced55,$deced70,$deced71,$deced714,$ranit06,$ranit25,$ranit55,$ranit70,$ranit71,$ranit714,$contam06,
$contam25,$contam55,$contam70,$contam71,$contam714,$anim_mari_contam,$anim_mari_moarte,$anim_mari_ranite,
$anim_mici_contam,$anim_mici_moarte,$anim_mici_ranite,$anim_pasari_contam,$anim_pasari_moarte,$anim_pasari_ranite,
$munitie_asanat_bombe_artilerie,$munitie_asanat_grenade,$munitie_asanat_grenade_defens,$munitie_asanat_proiectil,
$bombe_aviatie,$mine_antitanc,$mine_antipers,$mine_marine,$aruncator_gren,$muninfanterie,$alte_munitii,
$val_distr,$val_salv,$sursa_probabila,$mijloc_producere,$primul_mat_ars,$imprejur_determ,$despreob1,
$despreob2,$despreob3,$despreob4,$despreob5,$despreob6,$despreob7,$codsubst1,$codsubst2,$codsubst3,
$codsubst4,$numesubst1,$numesubst2,$numesubst3,$numesubst4,$codpericol1,$codpericol2,$codpericol3,$codpericol4,
$elib_subst_apa,$elib_subst_aer,$elib_subst_sol,$tip_radionuclid, $act_sursei,$debit_doza,$caract_sursa,$alte_masuri_protective,
$contramasuri,$contramasuri_scurt,$anticip_sever,$evol_inciden,$consecinte_even,$date_suplimentare,$zonademortalitate,
$distanta_adapostire,$zonadeintoxicatie,$distanta_evacuare,$profilaxiacuiod,$restrictiialimente1,$restrictiialimente2,
$restrictiialimente3,$restrictiialimente4,$restrictiialimente5,$restrictiialimente6,$dozaacumulata,$distanta1,
$distanta2,$distanta3,$distanta4,$distanta5,$distanta6,$distanta7,$distanta8,$doza1,$doza2,$doza3,$doza4,
$doza5,$doza6,$doza7,$doza8,$doza_int_sapt,$doza_int_luna,$doza_int_zi,$suprafata_afectata,$expl_mun,
$zona_afect,$nr_gospodarii,$asist_spec,$masuri_su,$poluaretransf,$verific_raport, $intravilan, $gradcontaminare, $telefon);
  $stmt->fetch();
    $this->resultarray = array($struct,$igsu,$isu,$subunit,$participanti,$tipsubunitate,$codsubunit,$categ_interv,$tip_interv,
$cod_interv,$alertare,$nume_victima,$svsu_spsualte,$tara,$judet,$localitati,$sate,$adresa,
$laty,$longx,$distanta_km,$plecare,$anunt,$sosire,$producere,$localizare,$lichidare,
$retragere,$sosiresvsu,$sosirespsu,$organtutelar,$tipproprietate,$codactivitateeconom,$tipobiectiv,
$cod_dest,$cos_fum,$forte_cerute_in_sprijin,$procedee_intrerupere,$comandant_actiune,$comandant_interventie,
$crestere_capacitate,$personal_destinat_ofiter,$personal_destinat_maistru,$personal_destinat_subofiter,
$personal_destinat_voluntar,$personal_destinat_primar,$personal_destinat_viceprimar,$personal_destinat_secretar,
$personal_destinat_svsu,$personal_destinat_spsu,$personal_destinat_politie,$personal_destinat_jandarmi,
$personal_destinat_frontiera,$personal_destinat_armata,$personal_destinat_cetateni,$mijstingere_isu,
$mijstingere_svsu,$mijstingere_spsu,$mijstingere_isu_tipb,$mijstingere_svsu_tipb,$mijstingere_spsu_tipb,
$mijstingere_isu_tipc,$mijstingere_svsu_tipc,$mijstingere_spsu_tipc,$mijstingere_isu_tipd,
$mijstingere_svsu_tipd,$mijstingere_spsu_tipd,$mijstingere_isu_tevigen,$mijstingere_svsu_tevigen,
$mijstingere_spsu_tevigen,$mijstingere_isu_refpulb,$mijstingere_svsu_refpulb,$mijstingere_spsu_refpulb,
$mijstingere_isu_autostin,$mijstingere_svsu_autosting,$mijstingere_spsu_autosting,$tipurgenta_multirisc_1,
$tipurgenta_multirisc_2,$tipurgenta_multirisc_3,$tipurgenta_multirisc_4,$tipurgenta_multirisc_svsu,
$tipurgenta_multirisc_spsu,$tipurgenta_pma2_1,$tipurgenta_pma2_2,$tipurgenta_pma2_3,$tipurgenta_pma2_4,
$tipurgenta_pma2_svsu,$tipurgenta_pma2_spsu,$tipurgenta_pma1_1,$tipurgenta_pma1_2,$tipurgenta_pma1_3,
$tipurgenta_pma1_4,$tipurgenta_pma1_svsu,$tipurgenta_pma1_spsu,$tipurgenta_asasmare_1,
$tipurgenta_asasmare_2,$tipurgenta_asasmare_3,$tipurgenta_asasmare_4,$tipurgenta_asasmare_svsu,
$tipurgenta_asasmare_spsu,$tipurgenta_asasmedie_1,$tipurgenta_asasmedie_2,$tipurgenta_asasmedie_3,
$tipurgenta_asasmedie_4,$tipurgenta_asasmedie_svsu,$tipurgenta_asasmedie_spsu,$tipurgenta_asasmica_1,
$tipurgenta_asasmica_2,$tipurgenta_asasmica_3,$tipurgenta_asasmica_4,$tipurgenta_asasmica_svsu,
$tipurgenta_asasmica_spsu,$tipurgenta_alteasas_1,$tipurgenta_alteasas_2,$tipurgenta_alteasas_3,
$tipurgenta_alteasas_4,$tipurgenta_alteasas_svsu,$tipurgenta_alteasas_spsu,$tipurgenta_aisi_1,
$tipurgenta_aisi_2,$tipurgenta_aisi_3,$tipurgenta_aisi_4,$tipurgenta_aisi_svsu,$tipurgenta_aisi_spsu,
$tipurgenta_aspfgi_1,$tipurgenta_aspfgi_2,$tipurgenta_aspfgi_3,$tipurgenta_aspfgi_4,$tipurgenta_aspfgi_svsu,
$tipurgenta_aspfgi_spsu,$tipurgenta_aservamop_1,$tipurgenta_aservamop_2,$tipurgenta_aservamop_3,
$tipurgenta_aservamop_4,$tipurgenta_aservamop_svsu,$tipurgenta_aservamop_spsu,$tipurgenta_crbnadp_1,
$tipurgenta_crbnadp_2,$tipurgenta_crbnadp_3,$tipurgenta_crbnadp_4,$tipurgenta_crbnadp_svsu,
$tipurgenta_crbnadp_spsu,$tipurgenta_aci_1,$tipurgenta_aci_2,$tipurgenta_aci_3,$tipurgenta_aci_4,
$tipurgenta_aci_svsu,$tipurgenta_aci_spsu,$tipurgenta_aspscaf_1,$tipurgenta_aspscaf_2,$tipurgenta_aspscaf_3,
$tipurgenta_aspscaf_4,$tipurgenta_aspscaf_svsu,$tipurgenta_aspscaf_spsu,$tipurgenta_barcisalupe_1,
$tipurgenta_barcisalupe_2,$tipurgenta_barcisalupe_3,$tipurgenta_barcisalupe_4,$tipurgenta_barcisalupe_svsu,
$tipurgenta_barcisalupe_spsu,$tipurgenta_afzm_1,$tipurgenta_afzm_2,$tipurgenta_afzm_3,$tipurgenta_afzm_4,
$tipurgenta_afzm_svsu,$tipurgenta_afzm_spsu,$tipurgenta_ambulante_1,$tipurgenta_ambulante_2,$tipurgenta_ambulante_3,
$tipurgenta_ambulante_4,$tipurgenta_ambulante_svsu,$tipurgenta_ambulante_spsu,$tipurgenta_descarc_1,
$tipurgenta_descarc_2,$tipurgenta_descarc_3,$tipurgenta_descarc_4,$tipurgenta_descarc_svsu,$tipurgenta_descarc_spsu,
$tipurgenta_asptransportapa_1,$tipurgenta_asptransportapa_2,$tipurgenta_asptransportapa_3,$tipurgenta_asptransportapa_4,
$tipurgenta_asptransportapa_svsu,$tipurgenta_asptransportapa_spsu,$tipurgenta_mptmpr_1,$tipurgenta_mptmpr_2,
$tipurgenta_mptmpr_3,$tipurgenta_mptmpr_4,$tipurgenta_mptmpr_svsu,$tipurgenta_mptmpr_spsu,$tipurgenta_alteautospeciale_1,
$tipurgenta_alteautospeciale_2,$tipurgenta_alteautospeciale_3,$tipurgenta_alteautospeciale_4,$tipurgenta_alteautospeciale_svsu,
$tipurgenta_alteautospeciale_spsu,$pers_salvate_adulti,$pers_salvate_copii,$pers_evacuate_adulti,$pers_evacuate_copii,
$deces_altesit_altep,$deces_altesit_copii,$deces_altesit_isu,$deces_altesit_svsu,$deces_ars_altep,$deces_ars_copii,
$deces_ars_isu,$deces_ars_svsu,$deces_asfix_altep,$deces_asfix_copii,$deces_asfix_isu,$deces_asfix_svsu,$ranit_altesit_copii,
$ranit_altesit_isu,$ranit_altesit_svsu,$ranit_altesitx_altep,$ranit_ars_altep,$ranit_ars_copii,$ranit_ars_isu,
$ranit_ars_svsu,$ranit_asfix_altep,$ranit_asfix_copii,$ranit_asfix_isu,$ranit_asfix_svsu,$deced06,$deced25,
$deced55,$deced70,$deced71,$deced714,$ranit06,$ranit25,$ranit55,$ranit70,$ranit71,$ranit714,$contam06,
$contam25,$contam55,$contam70,$contam71,$contam714,$anim_mari_contam,$anim_mari_moarte,$anim_mari_ranite,
$anim_mici_contam,$anim_mici_moarte,$anim_mici_ranite,$anim_pasari_contam,$anim_pasari_moarte,$anim_pasari_ranite,
$munitie_asanat_bombe_artilerie,$munitie_asanat_grenade,$munitie_asanat_grenade_defens,$munitie_asanat_proiectil,
$bombe_aviatie,$mine_antitanc,$mine_antipers,$mine_marine,$aruncator_gren,$muninfanterie,$alte_munitii,
$val_distr,$val_salv,$sursa_probabila,$mijloc_producere,$primul_mat_ars,$imprejur_determ,$despreob1,
$despreob2,$despreob3,$despreob4,$despreob5,$despreob6,$despreob7,$codsubst1,$codsubst2,$codsubst3,
$codsubst4,$numesubst1,$numesubst2,$numesubst3,$numesubst4,$codpericol1,$codpericol2,$codpericol3,$codpericol4,
$elib_subst_apa,$elib_subst_aer,$elib_subst_sol,$tip_radionuclid,$act_sursei,$debit_doza,$caract_sursa,$alte_masuri_protective,
$contramasuri,$contramasuri_scurt,$anticip_sever,$evol_inciden,$consecinte_even,$date_suplimentare,$zonademortalitate,
$distanta_adapostire,$zonadeintoxicatie,$distanta_evacuare,$profilaxiacuiod,$restrictiialimente1,$restrictiialimente2,
$restrictiialimente3,$restrictiialimente4,$restrictiialimente5,$restrictiialimente6,$dozaacumulata,$distanta1,
$distanta2,$distanta3,$distanta4,$distanta5,$distanta6,$distanta7,$distanta8,$doza1,$doza2,$doza3,$doza4,
$doza5,$doza6,$doza7,$doza8,$doza_int_sapt,$doza_int_luna,$doza_int_zi,$suprafata_afectata,$expl_mun,
$zona_afect,$nr_gospodarii,$asist_spec,$masuri_su,$poluaretransf,$verific_raport, $intravilan, $gradcontaminare, $telefon);
  $stmt->close();
  }

	public function getFisa(){
	      return $this->resultarray;
	}
}
?>
